name: Build APP

# manual and on push
on:
    workflow_dispatch:
    push:

jobs:
    build-website:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - uses: oven-sh/setup-bun@v2
        - run: bun install
        - run: bun run build
        - run: echo "" > .gitignore
        - run: |
            git config --global user.name 'Github Actions'
            git config --global user.email 'githubactions@users.noreply.github.com'
            git add dist
            git commit -m "Build website"
            git push
